---
editor: 
  markdown: 
    wrap: 72
---

# Cleans your data per your specifications and converts to tidy format

## Discard unused variables

```{r}
cirrhosis_data1 <- subset(cirrhosis_data, select = -c(Race,
                                                       Admissionroute,
                                                       Ptlocationpriortoadm, 
                                                       Admitlevelofcare,
                                                       Nondecompensationadmitreason, 
                                                       `Site coded`,
                                                       `Liverdiseaseetiology  section responses are Yes=1 0=No`,
                                                       he, 
                                                       Ascites,
                                                       `Baselinecomplications  Yes=1 0=No`, 
                                                       hcc, 
                                                       sbp,
                                                       Bleedingvarices, 
                                                       rrt,
                                                       Livertransplantationstatus,
                                                       `Comorbiditiespresent  Yes=1 0=No`,
                                                       Metastaticsolidtumor, 
                                                       Dischargedispo, 
                                                       Codestatus,
                                                       Dischargemednumber,
                                                       Underwentlivertrasnplantationaft, 
                                                       SeeninGIclinicafterthisadm,
                                                       Childsclassadmission, 
                                                       CPSsumofavaiable, 
                                                       Dischargedispo_CAT,
                                                       `PATIENT_TIME_of total follow up`, 
                                                       READMISSION_INTERVAL,
                                                       `READMISSION_30day Yes=1 0=No`, 
                                                       LT_INTERVAL,
                                                       GI_CLINIC_interval,
                                                       GI_CLINIC_TOTAL_FOLLOWUP_INTERVA,
                                                       CHARLSON_CI,
                                                       `Indications for care during hospitalization  Yes=1 0=No`,
                                                       UGIB_primary_liver_dx, 
                                                       `NACSELD_ACLF_D1  Yes=1 0=No` )
                           )
cirrhosis_data1

```

# Joining

## Addition of an observation ID
```{r}
cirrhosis_data1 <- cirrhosis_data1 |> 
  mutate(ID = row_number()) |> 
  relocate(ID)

cirrhosis_data1
  
```
## Separation of the dataset in two distinct datasets

```{r}
df <- cirrhosis_data1 |> 
  select(c = ID,
         Sex,
         Medicalinsurance,
         `Age(Decade)atadmission`,
         Liverrelateddiagnosis1,
         Alcohol,
         hcv,
         hbv,
         nafld,
         Cryptogenic,
         PrimarySclerosingCholangitis,
         Autoimmunehepatitis,
         pbc,
         Otherliverdiseaseetiology,
         wbc,
         cps,
         los,
         readmissioninterrval,
         inr_within1day,
         bili_within1day,
         creat_within1day,
         albumin_within1day,
         na_within1day,
         MELD_within1day,
         Mortality_InHospital,
         `Mean arterial pressure`,
         starts_with("DX_"),
         MORTALITY_30_DAYS_postDC,
         MORTALITY_90_DAYS_postDC,
         `child Class 1=A 2=B 3=C`,
         Mortality_InHospital)

df_Comorbidities <- cirrhosis_data1 |> 
  select(c = ID,
         mi,
         chf,
         pvd,
         Cerebrovasculardisease,
         Dementia,
         Chronicpulmonorydisease,
         Rheumatologicaldisease,
         Pepticulcerdisease,
         Mildliverdisease,
         Diabetes,
         Diabeteswithchroniccomplications,
         Heiplegiaorparaplegia,
         Renaldisease,
         Anymalignancyincludinglymphomaor,
         Moderateorsevereliverdisease,
         aids
         )
```

