---
title: "07_analysis3"
author: "s231932"
format: html
editor: visual
---

Descriptive statistics, how many in each group, etc.

## Stacked bar plot for age distribution by gender

```{r}

bar_plot_age_gender <- dat_aug_03 |>
  ggplot(aes(x = Age, 
             fill = Sex)) +
  geom_bar(position = "stack", 
           stat = "count", 
           alpha = 0.7) +
  labs(title = "Overview of age and gender repartition for patients with cirrhosis",
       x = "Age Group",
       y = "Count") +
  scale_fill_viridis_d() +
  theme_minimal() 
  
```

```{r}
ggsave("Age_gender.png", 
       path = "../results/plots/",
       plot = bar_plot_age_gender,
       width = 7,
       height = 5)
```

```{r}
bar_plot_age_gender
```

## Overview of the liver disease of the patient

```{r}
bar_plot_LD_Mortality<- dat_aug_03 |> 
  ggplot(aes(x = Liver_disease, 
             fill = Mortality)) +
  geom_bar(position = "fill", 
           stat = "count", 
           alpha = 0.7) +
  labs(title = "Liver disease repartition in cyrrhosis patients, stratified by mortality",
       y = "Proportion") +
  scale_fill_viridis_d() +
  theme_minimal() +
  theme(axis.title.x=element_blank()) +
  scale_x_discrete(guide = guide_axis(angle = 25))

```

```{r}
ggsave("LD_Mortality.png", 
       path = "../results/plots/",
       plot = bar_plot_LD_Mortality,
       width = 7,
       height = 5)
```

```{r}
bar_plot_LD_Mortality
```


# Overview of comorbities in the patients' population 

```{r}
bar_plot_comorbidities <- dat_aug_03 |> 
  ggplot(aes(x = Comorbidities, 
             fill = Comorbidities)) +
  geom_bar(alpha = 0.7) +
  labs(title = "Overview of comorbidities across patients suffering from cirrhosis ",
       y = "Count") +
  scale_fill_viridis_d() +
  theme_minimal() +
  theme(axis.text.x=element_blank(), 
        legend.title=element_blank()) 

```

```{r}
ggsave("Overrview_Comorbidities.png", 
       path = "../results/plots/",
       plot = bar_plot_comorbidities,
       width = 7,
       height = 5)
```

```{r}
bar_plot_comorbidities
```

# Overview of ethiology factor across population 

```{r}
bar_plot_ethiology <- dat_aug_03 |> 
  ggplot(aes(x = Etiologies, 
             fill = Etiologies)) +
  geom_bar(alpha = 0.7) +
  labs(title = "Overview of etiologies across patients suffering from cirrhosis ",
       y = "Count") +
  scale_fill_viridis_d() +
  theme_minimal() +
  theme(axis.text.x=element_blank(), 
        legend.title=element_blank()) 

```

```{r}
ggsave("Overview_Ethiology.png", 
       path = "../results/plots/",
       plot = bar_plot_ethiology,
       width = 7,
       height = 5)
```

```{r}
bar_plot_ethiology
```
