```{r}
dat_mortality <- dat_aug_03 |> 
  mutate(Alcohol = ifelse(Etiologies == "Alcohol_consumption", "yes", "no")) |> 
  mutate(NAFLD = ifelse(Etiologies == "Non_alcoolic_fatty_LD", "yes", "no")) |> 
  mutate(Cryptogenic = ifelse(Etiologies == "Cryptogenic", "yes", "no")) 

```

## Age impact on mortality

```{r}

ggplot(
  data = dat_mortality,
  mapping = aes(x = Age,
                fill = Mortality,
                na.rm = TRUE)
) +
  geom_bar(alpha = 0.6,
           position = "stack") +
  scale_fill_viridis_d() +
  labs(
  title = "Distribution of patient outcomes ",
  subtitle = "stratified by age",
  x = "Age",
  y = "Count"
)

```

```{r}
Age_impact_mortality <- ggplot(
  data = dat_aug_03,
  mapping = aes(x = Age,
                fill = Mortality,
                na.rm = TRUE)
) +
  geom_bar(alpha = 0.6,
           position = "fill") +
  scale_fill_viridis_d() +
  labs(
  title = "Distribution of patient outcomes ",
  subtitle = "stratified by age",
  x = "Age",
  y = "Proportions"
)

Age_impact_mortality
```


## Alcohol consumption impact on mortality

```{r}
ggplot(
  data = dat_aug_03,
  mapping = aes(x = Alcohol,
                fill = Mortality,
                na.rm = TRUE)
) +
  geom_bar(alpha = 0.6,
           position = "stack") +
  scale_fill_viridis_d() +
  labs(
  title = "Patient outcomes",
  subtitle = "stratified by alcohol consumption",
  x = "Alcohol consumption"
)
```

```{r}
Alcohol_impact_mortality <- ggplot(
  data = dat_mortality,
  mapping = aes(x = Alcohol,
                fill = Mortality,
                na.rm = TRUE)
) +
  geom_bar(alpha = 0.6,
           position = "fill") +
  scale_fill_viridis_d() +
  labs(
  title = "Distribution of patient outcomes ",
  subtitle = "stratified by alcohol consumption",
  x = "Alcohol consumption",
  y = "Proportions"
)

Alcohol_impact_mortality
```

## Comparing effects of different etiologies on mortality

 

```{r}
Alcohol_impact_mortality <- ggplot(
  data = dat_mortality,
  mapping = aes(x = NAFLD,
                fill = Mortality,
                na.rm = TRUE)
) +
  geom_bar(alpha = 0.6,
           position = "fill") +
  scale_fill_viridis_d() +
  labs(
  title = "Distribution of patient outcomes ",
  subtitle = "stratified by age",
  x = "Age",
  y = "Proportions"
)

Alcohol_impact_mortality
```

```{r}
Alcohol_impact_mortality <- ggplot(
  data = dat_mortality,
  mapping = aes(x = Cryptogenic,
                fill = Mortality,
                na.rm = TRUE)
) +
  geom_bar(alpha = 0.6,
           position = "fill") +
  scale_fill_viridis_d() +
  labs(
  title = "Distribution of patient outcomes ",
  subtitle = "stratified by age",
  x = "Age",
  y = "Proportions"
)

Alcohol_impact_mortality
```

# Saving the plot

```{r}
ggsave("Alcohol_impact_mortality.png", 
       path = "../results/plots/",
       plot = Alcohol_impact_mortality,
       width = 7,
       height = 5)
```

# LD Mortality 


```{r}
bar_plot_LD_Mortality<- dat_aug_03 |> 
  ggplot(aes(x = Liver_disease, 
             fill = Mortality)) +
  geom_bar(position = "fill", 
           stat = "count", 
           alpha = 0.7) +
  labs(title = "Liver disease repartition in cyrrhosis patients, stratified by mortality",
       y = "Proportion") +
  scale_fill_viridis_d() +
  theme_minimal() +
  theme(axis.title.x=element_blank()) +
  scale_x_discrete(guide = guide_axis(angle = 25))

```

```{r}
ggsave("LD_Mortality.png", 
       path = "../results/plots/",
       plot = bar_plot_LD_Mortality,
       width = 7,
       height = 5)
```

```{r}
bar_plot_LD_Mortality
```

# CPS Mortality 
