# Relation between Charlson value and the type of comorbidities

Charlson value represents a comorbidity index that predicts 10y life expectancy 
for people with multiple comorbidities


```{r}

box_plot_Charlson_Comorbidities <- dat_aug_03 |> 
  ggplot(mapping = aes(x = Comorbidities,
                       y = Charlson_CI, 
                       color = Comorbidities)) +
  geom_boxplot() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  labs(title = 'Impact of diverse comorbidities on the 10 year life expectancy of patients',
       y = 'Charlson Comorbidity Index') +
  theme_minimal() +
  theme(axis.text.x=element_blank(), 
        legend.title = element_blank(), 
        legend.text = element_text(size = 7))

```

```{r}
box_plot_Charlson_Comorbidities
```
```{r}
ggsave("Charlson_comorbidities.png", 
       path = "../results/plots/",
       plot = box_plot_Charlson_Comorbidities,
       width = 7,
       height = 5)
```

# Relation between Charlson value and the type of liver disease

```{r}

box_plot_Charlson_LD <- dat_aug_03 |> 
  ggplot(mapping = aes(x = Liver_disease,
                       y = Charlson_CI, 
                       color = Liver_disease)) +
  geom_boxplot() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  labs(title = 'Impact of diverse liver diseases on the 10 year life expectancy of patients',
       y = 'Charlson Comorbidity Index') +
  theme_minimal() +
  theme(axis.text.x=element_blank(), 
        legend.title = element_blank(), 
        legend.text = element_text(size = 7))

```

```{r}
box_plot_Charlson_LD
```

