# Liver disease and comordities relations 

```{r}
library(viridis)
```


```{r}
stacked_bar_liverDisease <- dat_aug_03 |>
  select(Liver_disease, Comorbidities) |> 
  count(Liver_disease, Comorbidities)|>
  rename(d_c_count = n) |> 
  arrange(Liver_disease, desc(d_c_count)) |>
  mutate(Comorbidities = fct_inorder(Comorbidities))
```

```{r}
stacked_bar_liverDisease 
```


```{r}

ggplot(dat_aug_03, 
       aes(x = Liver_disease,
           fill = Comorbidities)) +
  geom_bar() +
  scale_fill_viridis(discrete = TRUE, option = "D") +
  labs(title = "Hospitalizations by Liver Disease and Comorbidities",
       x = "Liver Disease",
       y = "Hospitalizations") +
  theme_minimal() +
  theme(legend.position = "right",
        legend.key.height= unit(0.4, 'cm'),
        legend.key.width= unit(0.2, 'cm')) +
  coord_flip()
```

```{r}
test2 <- stacked_bar_liverDisease |>
  filter(d_c_count<87)
```


```{r}
ggplot(stacked_bar_liverDisease, 
       aes(Liver_disease, Comorbidities)) +
  geom_tile(aes(fill= d_c_count))+
  labs(fill = "Count" ,
       title = "Hospitalizations by Liver Disease and Comorbidities",
       x = "Liver Disease",
       y = "Comorbidities") +
  scale_fill_viridis() +
  theme_classic()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```


# LD + Etiology by count 

```{r}
dat_aug_03_1 <- dat_aug_03 |> 
  group_by(Liver_disease, Etiologies) |> 
  summarise(count1 = n()) |> 
  ungroup()

```

```{r}
ggplot(dat_aug_03_1, 
       aes(x = Liver_disease, 
           y = Etiologies, 
           fill = count/nrow(dat_aug_03))) +
  geom_tile()+
  labs(title = "Hospitalizations by Liver Disease and their Etiology",
       x = "Liver Disease",
       y = "Etiologies", 
       fill = "Percent of patients") +
  scale_fill_viridis()+
  theme_classic()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

```

# LD + Etiology by mortality  


```{r}
dat_aug_03_1
```

```{r}
dat_aug_03_2 <- dat_aug_03 |> 
  filter(Mortality != 'No death') |> 
  group_by(Liver_disease, Etiologies, Mortality) |> 
  summarise(count2 = n())

```
```{r}
dat_aug_03_2
```
```{r}
dat_aug_03_join <- left_join(dat_aug_03_1, dat_aug_03_2, by = c("Liver_disease", "Etiologies"))
```

```{r}
dat_aug_03_join <- dat_aug_03_join |> 
  replace_na(list(count2 = 0))
```

```{r}
ggplot(dat_aug_03_join, 
       aes(x = Liver_disease, 
           y = Etiologies, 
           fill = count2/count1)) +
  geom_tile() +
  labs(title = "Repartition of death according to Liver Disease and Etiology",
       x = "Liver Disease",
       y = "Etiologies", 
       fill = "Percent of dead patients") +
  scale_fill_viridis()+
  theme_classic()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

```

```{r}
install.packages("treemapify")
library(treemapify)
```


```{r}
ggplot(stacked_bar_liverDisease, aes(area = d_c_count, fill = Liver_disease)) +
  geom_treemap()
```

```{r}
ggplot(stacked_bar_liverDisease, aes(area = d_c_count,
                                     fill = Liver_disease,
                                     label = Comorbidities, 
                                     subgroup = Liver_disease)) +
  geom_treemap() +
	geom_treemap_subgroup_border() +
	geom_treemap_text(colour = "white", place = "topleft", reflow = T) +
  scale_color_viridis_d()
```

```{r}
bubble_order <- c("UGIB due to portal hypertension",
                  "Jaundice- as isolated presentation",
                  "Hepatic encephalopathy",
                  "Hepato-hydrothorax",
                  "HCC or cholangioca.",
                  "Alcoholic hepatitis",
                  "Other fluid overload",
                  "Ascites",
                  "SBP",
                  "AKI")
bubble_chart <- stacked_bar_liverDisease |>
  arrange(match(Liver_disease,bubble_order))

```


```{r}

ggplot(bubble_chart,
       aes(x = factor(Liver_disease, bubble_order), 
           y = Comorbidities,
           colour = Liver_disease,
           size = d_c_count)) +
  geom_point() +
  geom_text(aes(label = d_c_count), 
            colour = "white", 
            size = 3) +
  scale_x_discrete(position = "top") +
  scale_color_viridis_d() +
  scale_size_continuous(range = c(3, 9)) +
  labs(x = NULL, y = NULL, title= "Comorbidities by Liver Disease") +
  theme(legend.position = "none",
        panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 0))
```

